apiVersion: v1
kind: Service
metadata:
  labels:
    app: partners-payments
    environment: Development
  name: partners-payments
  namespace: services
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: 5000
  selector:
    app: partners-payments
  sessionAffinity: None
  type: ClusterIP
